openapi: "3.0.2"
info: # Belum ditentukan data info dan servers
  title: Events App
  description: description Events App
  termsOfService: https://academy.alterra.id
  contact:
    name: API Support
    url: https://www.alterra.id/support
    email: support@alterra.id
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0"
externalDocs:
  description: alterra external docs API
  url: https://alterra.id
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/fazamttqn/EventsApp/1.0.0
  - url: https://{environment}.api.alterra.id/v1
    description: ALTA API server
    variables:
      environment:
        default: dev
        enum:
          - dev
          - staging
          - production
  - url: http://13.215.249.83:80
    description: ALTA API server
tags:
  - name: Login
    description: User Authentication
  - name: Register
    description: Register User
  - name: User
    description: User data management
  - name: Event
    description: Event data management
  - name: Participation
    description: Participation data management
paths:
  ###########################
  #          LOGIN          #
  ###########################
  /login:
    post:
      tags:
        - Login
      summary: login user
      description: Login user description
      requestBody:
        content:
          application/json:
            # schema:
            # $ref: "#component/schemas/requestLogin"
            examples:
              userData:
                description: "Data user"
                value: { email: "alta@alterra.id", password: "inipassword" }
                # type: object
                # properties:
                #   email:
                #     type: string
                #     examples: alta@mail.com
                #   password:
                #     type: string
                #     examples: inipassword
      responses:
        "200":
          description: "Login Success"
          content:
            application/json:
              # schema:
              # $ref: "#/components/schemas/responseLoginSuccess"
              examples:
                responseData:
                  description: response success
                  value:
                    {
                      code: 200,
                      status: "Success",
                      message: "Login Success",
                      data:
                        {
                          id: 1,
                          token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MzgzMjYxODAsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJhZG1pbiJ9.AebFR-oQjUSOMez2ucDWkiMrS2eQIPmcYm5c71qZ_co",
                        },
                    }
        "400":
          description: "Login Failed"
          content:
            application/json:
              # schema:
              # $ref: "#/components/schemas/failedResponseLogin"
              examples:
                responseData:
                  description: response failed
                  value:
                    { code: 400, status: "failed", message: "Login Failed" }
  ##############################
  #          REGISTER          #
  ##############################
  /register:
    post:
      tags:
        - Register
      summary: Register user
      description: Register user description
      requestBody:
        content:
          application/json:
            # schema:
            # $ref: "#component/schemas/requestRegister"
            examples:
              userData:
                description: "Data user"
                value:
                  {
                    name: Budi Setiawan,
                    email: budi@gmail.com,
                    password: inibudi,
                  }
                # type: object
                # properties:
                #   email:
                #     type: string
                #     examples: alta@mail.com
                #   password:
                #     type: string
                #     examples: inipassword
      responses:
        "200":
          description: "Register Success"
          content:
            application/json:
              # schema:
              # $ref: "#/components/schemas/responseRegisterSuccess"
              examples:
                responseData:
                  description: response success
                  value:
                    {
                      code: 200,
                      status: "Success",
                      message: "Register Success",
                    }
        "400":
          description: "Register Failed"
          content:
            application/json:
              # schema:
              # $ref: "#/components/schemas/failedResponseRegister"
              examples:
                responseData:
                  description: response failed
                  value:
                    {
                      code: 400,
                      status: "failed",
                      message: "All input data must be filled",
                    }
  ##########################
  #          USER          #
  ##########################
  /users:
    get:
      tags:
        - User
      summary: profile user
      description: Profile user description
      responses:
        "200":
          description: "Get Profile Success"
          content:
            application/json:
              # schema:
              # $ref: "#/components/schemas/responseOneUserSuccess"
              examples:
                responseData:
                  description: response success
                  value:
                    {
                      code: 200,
                      status: "Success",
                      message: "Success get your data",
                      data:
                        {
                          ID: 1,
                          avatar: URL File,
                          name: "budi",
                          email: "budi@gmail.com",
                        },
                    }
        "400":
          description: "Failed Get Profile"
          content:
            application/json:
              # schema:
              # $ref: "#/components/schemas/failedResponseOneUserSuccess"
              examples:
                responseData:
                  description: response failed
                  value:
                    {
                      code: 400,
                      status: "failed",
                      message: "Failed to get your data",
                    }
  /users/{id}:
    put:
      tags:
        - User
      summary: update user
      description: Updated user description
      requestBody:
        content:
          application/json:
            # schema:
            # $ref: "#component/schemas/requestUpdateUser"
            examples:
              userData:
                description: "Data user"
                value:
                  {
                    name: Angga pramaja,
                    email: angga@gmail.com,
                    password: ituangga,
                  }
                # type: object
                # properties:
                #   email:
                #     type: string
                #     examples: alta@mail.com
                #   password:
                #     type: string
                #     examples: inipassword
      responses:
        "200":
          description: "Update Success"
          content:
            application/json:
              # schema:
              # $ref: "#/components/schemas/responseUpdatedUser"
              examples:
                responseData:
                  description: response success
                  value:
                    { code: 200, status: "Success", message: "Update Success" }
        "400":
          description: "Failed Updated"
          content:
            application/json:
              # schema:
              # $ref: "#/components/schemas/failedResponseUpdatedUser"
              examples:
                responseData:
                  description: response failed
                  value:
                    { code: 400, status: "failed", message: "Failed Update" }
    delete:
      tags:
        - User
      summary: delete user
      description: Delete user description
      responses:
        "200":
          description: Delete Success
          content:
            application/json:
              # schema:
              # $ref: "#/components/schemas/responseDeleteUserSuccess"
              examples:
                responseData:
                  description: response success
                  value:
                    { code: 200, status: "Success", message: "Delete Success" }
        "400":
          description: Failed Deleted
          content:
            application/json:
              # schema:
              # $ref: "#/components/schemas/failedResponseDeleteUser"
              examples:
                responseData:
                  description: response failed
                  value:
                    { code: 400, status: "failed", message: "Failed deleted" }
  ############################
  #          EVENTS          #
  ############################
  /events:
    post:
      tags:
        - Event
      summary: create events
      description: Create events description
      requestBody:
        content:
          application/json:
            # schema:
            # $ref: "#component/schemas/requestInsertEvent"
            examples:
              eventData:
                description: "Create event description by user"
                value:
                  {
                    photo_events: URL,
                    name: Webinar Pendidikan,
                    hosted_by: Company Surya Kencana,
                    date: 20-07-2022,
                    city: Jakarta,
                    location: (longitude and latitude),
                    details: Ini adalah description webinar bertema pendidikan,
                  }
                # type: object
                # properties:
                #   email:
                #     type: string
                #     examples: alta@mail.com
                #   password:
                #     type: string
                #     examples: inipassword
      responses:
        "200":
          description: "Success to create event"
          content:
            application/json:
              # schema:
              # $ref: "#/components/schemas/responseInsertEvent"
              examples:
                responseData:
                  description: response success
                  value:
                    {
                      code: 200,
                      status: "Success",
                      message: "Success insert event",
                    }
        "400":
          description: "Failed to create event"
          content:
            application/json:
              # schema:
              # $ref: "#/components/schemas/failedResponseInsertEvent"
              examples:
                responseData:
                  description: response failed
                  value:
                    {
                      code: 400,
                      status: "failed",
                      message: "Failed insert event",
                    }
    get:
      tags:
        - Event
      summary: get all events
      description: Home description
      responses:
        "200":
          description: "Get all events success"
          content:
            application/json:
              # schema:
              # $ref: "#/components/schemas/responseHomeSuccess"
              examples:
                responseHome:
                  description: response home success
                  value:
                    {
                      code: 200,
                      status: "Success",
                      message: "Success get all events",
                      data:
                        [
                          {
                            photo_events: URL,
                            name: Webinar Pendidikan,
                            hosted_by: Company Surya Kencana,
                            date: 20-07-2022,
                            city: Jakarta,
                            location: (longitude and latitude),
                            details: Ini adalah description webinar bertema pendidikan,
                          }
                        ],
                    }
        "400":
          description: "Failed to get all events"
          content:
            application/json:
              # schema:
              # $ref: "#/components/schemas/faileResponseHomeSuccess"
              examples:
                responseData:
                  description: response home failed
                  value:
                    {
                      code: 400,
                      status: "failed",
                      message: "Failed get all events",
                    }
  /events/{id_event}:
    get:
      tags:
        - Event
      summary: get event
      description: Show one event
      responses:
        "200":
          description: "Get events success"
          content:
            application/json:
              # schema:
              # $ref: "#/components/schemas/responseOneEventSuccess"
              examples:
                responseData:
                  description: response event success
                  value:
                    {
                      code: 200,
                      status: "Success",
                      message: "Success get event",
                      data:
                        {
                          photo_events: URL,
                          name: Webinar Pendidikan,
                          hosted_by: Company Surya Kencana,
                          date: 20-07-2022,
                          city: Jakarta,
                          location: (longitude and latitude),
                          details: Ini adalah description webinar bertema pendidikan,
                        },
                    }
        "400":
          description: "Failed to get events"
          content:
            application/json:
              # schema:
              # $ref: "#/components/schemas/failedOneEventSuccess"
              examples:
                responseData:
                  description: response event failed
                  value:
                    {
                      code: 400,
                      status: "failed",
                      message: "Failed to get event",
                    }
    put:
      tags:
        - Event
      summary: update event
      description: Updated event description
      requestBody:
        content:
          application/json:
            # schema:
            # $ref: "#component/schemas/requestUpdateEvent"
            examples:
              eventData:
                description: "Update event Description by user"
                value:
                  {
                    photo_events: URL,
                    name: Webinar Pendidikan,
                    hosted_by: Company Surya Kencana,
                    date: 20-07-2022,
                    city: Jakarta,
                    location: (longitude and latitude),
                    details: Ini adalah description webinar bertema pendidikan,
                  }
                # type: object
                # properties:
                #   email:
                #     type: string
                #     examples: alta@mail.com
                #   password:
                #     type: string
                #     examples: inipassword
      responses:
        "200":
          description: "Update Success"
          content:
            application/json:
              # schema:
              # $ref: "#/components/schemas/responseUpdateEvent"
              examples:
                responseData:
                  description: response success
                  value:
                    { code: 200, status: "Success", message: "Success update event" }
        "400":
          description: "Failed Updated"
          content:
            application/json:
              # schema:
              # $ref: "#/components/schemas/failedResponseUpdateEvent"
              examples:
                responseData:
                  description: response failed
                  value:
                    { code: 400, status: "failed", message: "Failed update event" }
    delete:
      tags:
        - Event
      summary: delete event
      description: Delete event description
      responses:
        "200":
          description: Delete Success
          content:
            application/json:
              # schema:
              # $ref: "#/components/schemas/responseDeleteEventSuccess"
              examples:
                responseData:
                  description: response success
                  value:
                    { code: 200, status: "Success", message: "Delete event success" }
        "400":
          description: Failed Deleted
          content:
            application/json:
              # schema:
              # $ref: "#/components/schemas/failedResponseDeleteEvent"
              examples:
                responseData:
                  description: response failed
                  value:
                    { code: 400, status: "failed", message: "Failed event deleted" }

  ###################################
  #          PARTICIPATION          #
  ###################################
  

